name: multicolorfits
channels:
    - defaults
dependencies:
    - "python>=3.5"
    - setuptools
    - numpy
    - numpydoc
    - scipy
    - "astropy>=3.1"
    - pip:
      - -e ..
      - "sphinx<=1.8.5"
      - sphinx_rtd_theme
      - sphinx_automodapi
      - matplotlib
      - pyregion
      - pyqt5 
      - astropy
      - pyface
      - traits
      - traitsui
      - scikit-image
- lxml
